apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8084
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 443
        hostPort: 8444
        listenAddress: 127.0.0.1
        protocol: TCP
