apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k-comms-staging
resources:
  - ../staging
patches:
  - path: configmap-patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: k-comms
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - comms.k-comms.test
          - objects.k-comms.test
      - op: replace
        path: /spec/rules/0/host
        value: comms.k-comms.test
      - op: replace
        path: /spec/rules/1/host
        value: objects.k-comms.test
images:
  - name: ghcr.io/soyuz-tec/k-comms
    newName: localhost/k-comms
    newTag: local-proof
