apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k-comms-edge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k-comms-edge
  minReplicas: 3
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
