apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k-comms
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - comms.example.invalid
      secretName: k-comms-production-tls
  rules:
    - host: comms.example.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k-comms-edge
                port:
                  name: http
