defmodule CommsCore.Attachments.AttachmentVariant do
  @moduledoc """
  A derived rendition of an attachment stored as its own object.

  A variant is generated by the client, so it is untrusted content that is
  nonetheless rendered inline rather than downloaded. Its content type is
  therefore restricted to non-executable raster formats here, in the database
  constraint, and again in the storage adapter that signs the upload.
  """

  use CommsCore.Schema

  @kinds [:thumbnail]
  @content_types ["image/webp", "image/jpeg", "image/png"]
  @max_bytes 524_288

  schema "attachment_variants" do
    field(:tenant_id, Ecto.UUID)
    field(:attachment_id, Ecto.UUID)
    field(:kind, Ecto.Enum, values: @kinds)
    field(:object_key, :string)
    field(:content_type, :string)
    field(:byte_size, :integer)
    field(:checksum_sha256, :string)
    field(:object_version_id, :string)
    field(:uploaded_at, :utc_datetime_usec)
    # The owning attachment is referenced by id only. A `belongs_to` back to
    # Attachment would close a module cycle with its `has_many`, which the
    # boundary rules reject; preloading runs from the attachment side.
    timestamps()
  end

  def kinds, do: @kinds
  def content_types, do: @content_types
  def max_bytes, do: @max_bytes

  def changeset(value, attrs) do
    value
    |> cast(attrs, [
      :tenant_id,
      :attachment_id,
      :kind,
      :object_key,
      :content_type,
      :byte_size,
      :checksum_sha256,
      :object_version_id,
      :uploaded_at
    ])
    |> validate_required([
      :tenant_id,
      :attachment_id,
      :kind,
      :object_key,
      :content_type,
      :byte_size,
      :checksum_sha256
    ])
    |> validate_inclusion(:content_type, @content_types)
    |> validate_number(:byte_size, greater_than: 0, less_than_or_equal_to: @max_bytes)
    |> validate_format(:checksum_sha256, ~r/^[a-f0-9]{64}$/)
    |> unique_constraint(:object_key)
    |> unique_constraint([:attachment_id, :kind],
      name: :attachment_variants_attachment_kind_unique
    )
    |> check_constraint(:kind, name: :attachment_variants_kind_allowed)
    |> check_constraint(:content_type, name: :attachment_variants_content_type_allowed)
    |> check_constraint(:byte_size, name: :attachment_variants_byte_size_bounded)
    |> check_constraint(:checksum_sha256, name: :attachment_variants_checksum_format)
    |> check_constraint(:object_version_id,
      name: :attachment_variants_verification_consistent
    )
  end

  @doc """
  Reports whether the variant names an object that actually exists.

  Intent alone is not proof: the version arrives only once the object store has
  confirmed the upload.
  """
  def verified?(%__MODULE__{object_version_id: version}) when is_binary(version),
    do: version not in ["", "null"]

  def verified?(_variant), do: false
end
