import Config

config :elixir, :time_zone_database, Tzdata.TimeZoneDatabase
config :tzdata, :autoupdate, :disabled
config :mime, :types, %{"application/scim+json" => ["scim"]}

config :comms_core,
  ecto_repos: [CommsCore.Repo],
  conversation_call_lifecycle_adapter: CommsCore.AudioCalls,
  conversation_whiteboard_reclamation_adapter: CommsCore.Whiteboards,
  identity_conversation_bootstrap_adapter: CommsCore.Conversations,
  matrix_eligibility_adapter: CommsCore.Conversations.PrivateRoomEligibility,
  identity_call_lifecycle_adapter: CommsCore.AudioCalls.LifecycleCoordinator,
  identity_notification_adapter: CommsCore.Notifications,
  matrix_access_protection_adapter: CommsCore.Governance.MatrixAccessProtection,
  matrix_provisioning_adapter: CommsIntegrations.SynapseIdentity,
  matrix_client_provisioning_enabled: false,
  private_rooms_enabled: false,
  private_room_control_adapter: CommsIntegrations.SynapsePrivateRooms,
  private_room_protection_adapter: CommsCore.Governance.PrivateRoomProtection,
  private_event_adapter: CommsIntegrations.SynapsePrivateEvents,
  private_content_erasure_adapter: CommsCore.Messaging,
  tenant_call_lifecycle_adapter: CommsCore.AudioCalls.LifecycleCoordinator,
  tenant_authorization_actor_adapter: CommsCore.Accounts,
  tenant_identity_access_adapter: CommsCore.Accounts,
  tenant_invitation_identity_adapter: CommsCore.Accounts,
  telephony_callback_adapter: CommsIntegrations.Telephony.LiveKit,
  telephony_control_adapter: CommsIntegrations.Telephony.LiveKit,
  oidc: %{enabled: false},
  direct_audio_p2p_enabled: false,
  artifact_provider_adapter: CommsIntegrations.MeetingArtifacts.LiveKitEgress,
  artifact_storage_adapter: CommsIntegrations.MeetingArtifacts.S3Storage,
  artifact_transcription_adapter: CommsIntegrations.MeetingArtifacts.WhisperTranscription,
  artifact_protection_adapter: CommsCore.Governance.ArtifactProtection,
  voicemail_provider_adapter: CommsIntegrations.Telephony.VoicemailARI,
  voicemail_storage_adapter: CommsIntegrations.Telephony.VoicemailS3,
  voicemail_protection_adapter: CommsCore.Governance.VoicemailProtection,
  whiteboard_asset_adapter: CommsCore.Messaging.BoardAssets,
  meeting_artifact_policy: [
    privacy_approved: false,
    provider_qualified: false,
    enabled_tenant_ids: []
  ],
  notification_availability_notifier: CommsWeb.NotificationAvailabilityNotifier,
  audio_participant_eviction_enforcement_seconds: 660,
  instant_rooms_enabled: false,
  instant_room_tenant_slug: nil,
  instant_room_guest_idle_ttl_seconds: 3_600,
  instant_room_registered_idle_ttl_seconds: 86_400,
  instant_room_presence_heartbeat_seconds: 30,
  instant_room_presence_lease_seconds: 90,
  instant_room_reconnect_grace_seconds: 90,
  instant_room_max_participants: 25,
  job_workers: [
    audit_history_snapshot_purge: CommsWorkers.AuditHistorySnapshotPurgeWorker,
    audio_call_expiry: CommsWorkers.AudioCallExpiryWorker,
    audio_participant_eviction: CommsWorkers.AudioParticipantEvictionWorker,
    attachment_abandon: CommsWorkers.AttachmentAbandonWorker,
    attachment_abandon_reconciler: CommsWorkers.AttachmentCleanupReconcilerWorker,
    attachment_scan: CommsWorkers.AttachmentWorker,
    call_artifact: CommsWorkers.CallArtifactWorker,
    call_artifact_reconciler: CommsWorkers.CallArtifactReconcilerWorker,
    deletion: CommsWorkers.DeletionWorker,
    erasure_reconciler: CommsWorkers.ErasureReconcilerWorker,
    ephemeral_room_lifecycle: CommsWorkers.EphemeralRoomLifecycleWorker,
    ephemeral_room_reconciler: CommsWorkers.EphemeralRoomReconcilerWorker,
    matrix_device_reconciler: CommsWorkers.MatrixDeviceReconcilerWorker,
    private_room_purge_reconciler: CommsWorkers.PrivateRoomPurgeReconcilerWorker,
    guest_admission_expiry: CommsWorkers.GuestAdmissionExpiryWorker,
    meeting_reminder: CommsWorkers.MeetingReminderWorker,
    notification_delivery: CommsWorkers.NotificationWorker,
    outbox_publication: CommsWorkers.OutboxWorker,
    personal_content_cleanup: CommsWorkers.PersonalContentCleanupWorker,
    retention: CommsWorkers.RetentionWorker,
    retention_reconciler: CommsWorkers.RetentionReconcilerWorker,
    telephony_cleanup: CommsWorkers.TelephonyCleanupWorker,
    telephony_control: CommsWorkers.TelephonyControlWorker,
    telephony_dispatch: CommsWorkers.TelephonyDispatchWorker,
    telephony_expiry: CommsWorkers.TelephonyExpiryWorker,
    telephony_routing: CommsWorkers.TelephonyRoutingWorker,
    telephony_voicemail: CommsWorkers.TelephonyVoicemailWorker,
    webhook_delivery: CommsWorkers.WebhookWorker
  ],
  attachment_cleanup_grace_seconds: 300,
  attachment_cleanup_claim_timeout_seconds: 900,
  attachment_cleanup_reconcile_limit: 100,
  push_delivery_status: :unavailable,
  session_ttl_seconds: 2_592_000,
  session_absolute_ttl_seconds: 2_592_000

config :comms_core, CommsCore.Repo,
  migration_primary_key: [name: :id, type: :binary_id],
  migration_foreign_key: [type: :binary_id]

config :comms_core, Oban,
  repo: CommsCore.Repo,
  queues: [
    default: 10,
    lifecycle: 10,
    notifications: 10,
    webhooks: 10,
    media: 5,
    telephony: 2,
    outbox: 10
  ],
  plugins: [
    {Oban.Plugins.Pruner, max_age: 86_400},
    {Oban.Plugins.Cron,
     crontab: [
       {"* * * * *", CommsWorkers.AttachmentCleanupReconcilerWorker},
       {"* * * * *", CommsWorkers.CallArtifactReconcilerWorker},
       {"* * * * *", CommsWorkers.ErasureReconcilerWorker},
       {"0 * * * *", CommsWorkers.AuditHistorySnapshotPurgeWorker},
       {"0 * * * *", CommsWorkers.RetentionReconcilerWorker},
       {"0 * * * *", CommsWorkers.PersonalContentCleanupWorker},
       {"* * * * *", CommsWorkers.EphemeralRoomReconcilerWorker},
       {"* * * * *", CommsWorkers.MatrixDeviceReconcilerWorker},
       {"* * * * *", CommsWorkers.PrivateRoomPurgeReconcilerWorker}
     ]}
  ]

config :comms_integrations,
  allow_insecure_local_object_storage: false,
  allow_insecure_local_media: false,
  audio_provider_mode: "disabled",
  telephony_provider_mode: "disabled",
  telephony_transfer_enabled: false,
  telephony_transfer_destination_prefixes: [],
  telephony_pbx_enabled: false,
  telephony_pbx_qualified: false,
  telephony_pbx_api_url: nil,
  telephony_pbx_username: nil,
  telephony_pbx_password: nil,
  telephony_pbx_endpoint: nil,
  telephony_pbx_application: "k-comms",
  telephony_pbx_destination_prefixes: [],
  telephony_pbx_webhook_secret: nil,
  telephony_voicemail_storage_qualified: false,
  telephony_ring_timeout_seconds: 45,
  telephony_max_duration_seconds: 1_800,
  audio_token_ttl_seconds: 300,
  livekit_api_url: nil,
  livekit_api_key: nil,
  livekit_api_secret: nil,
  livekit_server_url: nil,
  notification_adapter: CommsIntegrations.Notifications.Log,
  object_storage_adapter: CommsIntegrations.ObjectStorage.S3,
  scanner_adapter: CommsIntegrations.Scanner.Log,
  webhook_adapter: CommsIntegrations.Webhooks.Http,
  webhook_allowed_hosts: [],
  webhook_http: [allowed_hosts: [], allowed_ports: [443], timeout_ms: 10_000]

config :comms_integrations, :artifact_transcription,
  enabled: false,
  qualified: false,
  origin: nil,
  max_media_bytes: 26_214_400,
  max_response_bytes: 1_048_576,
  timeout_ms: 30_000,
  model: "whisper-1"

config :comms_web,
  generators: [binary_id: true],
  auth_adapter: CommsWeb.Auth.Token,
  access_token_ttl_seconds: 900,
  allow_bootstrap: false,
  direct_audio_join_rate_limit: 8,
  direct_audio_p2p_enabled: false,
  direct_audio_signal_byte_limit: 262_144,
  direct_audio_signal_rate_limit: 240,
  direct_audio_stun_urls: ["stun:stun.cloudflare.com:3478"],
  immersive_mode_enabled: false,
  instant_room_creation_rate_limits_enabled: true,
  insecure_lan_release: false,
  hsts: false,
  csp_connect_sources: [
    "'self'",
    "http://localhost:4000",
    "ws://localhost:4000",
    "http://localhost:9000",
    "ws://127.0.0.1:7880"
  ],
  cors_origins: ["http://localhost:5173", "http://127.0.0.1:5173"]

config :comms_web, CommsWeb.Endpoint,
  url: [host: "localhost"],
  adapter: Bandit.PhoenixAdapter,
  render_errors: [formats: [json: CommsWeb.ErrorJSON], layout: false],
  pubsub_server: CommsWeb.PubSub

config :phoenix, :filter_parameters, [
  "access_token",
  "authorization",
  "conversion_verification_code",
  "current_password",
  "new_password",
  "password",
  "code",
  "challenge_token",
  "client_secret",
  "recovery_code",
  "totp_secret",
  "mfa_code",
  "credential_token",
  "refresh_token",
  "secret",
  "socket_ticket",
  "token",
  "verification_code"
]

config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id, :tenant_id, :actor_id, :conversation_id, :job_id]

import_config "#{config_env()}.exs"
