apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: postgres
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: k-comms
      ports:
        - { protocol: TCP, port: 5432 }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: minio
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: k-comms
      ports:
        - { protocol: TCP, port: 9000 }
    - ports:
        - { protocol: TCP, port: 9000 }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-init-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: minio-init
  policyTypes: ["Egress"]
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: minio
      ports:
        - { protocol: TCP, port: 9000 }
