apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k-comms
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - comms.staging.example.invalid
        - objects.staging.example.invalid
      secretName: k-comms-staging-tls
  rules:
    - host: comms.staging.example.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k-comms-edge
                port:
                  name: http
    - host: objects.staging.example.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  name: api
